name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install snowflake-connector-python cryptography

      - name: Run Snowflake script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
        run: |
          python -c "
          import snowflake.connector
          from cryptography.hazmat.primitives.serialization import load_pem_private_key
          from cryptography.hazmat.backends import default_backend

          # Load the private key from a PEM file or string
          private_key_str = '''${{ secrets.SNOWFLAKE_PRIVATE_KEY }}'''

          # Decode the private key string to bytes
          private_key_bytes = private_key_str.encode()

          # Load the private key object
          private_key = load_pem_private_key(
              private_key_bytes,
              password='${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}'.encode(),
              backend=default_backend()
          )

          # Establish Snowflake connection using the private key object
          conn = snowflake.connector.connect(
              user='${{ secrets.SNOWFLAKE_USER }}',
              account='${{ secrets.SNOWFLAKE_ACCOUNT }}',
              private_key=private_key
          )

          # Execute your SQL script
          conn.cursor().execute('RUN YOUR SQL SCRIPT HERE')
          "
