name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install snowflake-connector-python cryptography

      - name: Run Snowflake script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
        run: |
          python -c "
          import snowflake.connector
          from cryptography.hazmat.primitives import serialization
          from cryptography.hazmat.backends import default_backend

          # Load the private key from GitHub secrets
          private_key = '''${{ secrets.SNOWFLAKE_PRIVATE_KEY }}'''
          
          # Convert private key string to bytes
          private_key_bytes = private_key.encode('utf-8')

          # Load the private key from PEM format
          private_key_obj = serialization.load_pem_private_key(
              private_key_bytes,
              password=None,  # If you have a passphrase, use it here
              backend=default_backend()
          )

          # Establish Snowflake connection with the correct private key
          conn = snowflake.connector.connect(
              user='${{ secrets.SNOWFLAKE_USER }}',
              account='${{ secrets.SNOWFLAKE_ACCOUNT }}',
              private_key=private_key_obj,  # Pass the RSAPrivateKey object
              private_key_passphrase='${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}'
          )

          # Execute your SQL script
          conn.cursor().execute('RUN YOUR SQL SCRIPT HERE')
          "
